/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'Custom';

  static const IconData globe = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData globe_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData chat_1 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData library_books = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData chat_2 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData tune = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData spin1 = const IconData(0xe830, fontFamily: _kFontFam);
}
